# Generated by Django 4.0 on 2022-01-07 04:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_account_businesscategory_alter_account_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget', models.IntegerField()),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('assigned', 'assigned'), ('pending', 'pending'), ('completed ', 'completed')], default='pending', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
