# Generated by Django 4.0 on 2022-01-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
