# Generated by Django 4.1.7 on 2023-03-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_bid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='plumber',
            new_name='technician',
        ),
    ]
