# Generated by Django 4.0 on 2022-01-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='businessCategory',
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('client', 'client'), ('plumber', 'plumber')], max_length=30),
        ),
        migrations.DeleteModel(
            name='BusinessCategory',
        ),
    ]
